package com.edusys.ui;

import com.edusys.utils.XImage;
import java.awt.Color;

public class HuongDanJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HuongDanJDialog
     */
    public HuongDanJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
void init()
{
    setIconImage(XImage.getAppIcon());
    setTitle("Edusys Hướng dẫn");
    setLocationRelativeTo(null);
    getContentPane().setBackground(Color.white);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Để sử dụng phần mềm hệ thống giáo dục Eudsys, bạn có thể làm theo các bước sau:\n\n1.Đăng nhập vào hệ thống: Truy cập vào trang web của Eudsys và sử dụng thông tin đăng nhập của bạn     để đăng nhập vào hệ thống.\n2.Giao diện chính: Sau khi đăng nhập thành công, bạn sẽ được chuyển đến giao diện chính của Eudsys. \n   Tại đây, bạn sẽ tìm thấy các chức năng và tính năng khác nhau.\n3.Quản lý hồ sơ nhân viên và học viên: Eudsys cho phép bạn quản lý hồ sơ nhân viên và học viên. Bạn có \n   thể tạo, chỉnh sửa, xem và xóa hồ sơ này theo nhu cầu. \n4.Quản lý khóa học: Bạn có thể tạo và quản lý khóa học trong hệ thống Eudsys. Có thể xóa khóa học với \n  vai trò là trưởng phòng\n5.Lập kế hoạch giảng dạy và quản lý chuyên đề: Eudsys cung cấp tính năng quản lý các chuyên đề.\n6.Báo cáo và thống kê: Eudsys cho phép bạn theo dõi thống kê về bảng điểm,người học, điểm từng chuyên đề và doanh thu. Bạn có thể xem báo cáo và thống kê về tiến độ học tập và thành tích của học sinh, và         sự phát triển của trung tâm theo năm\n7.Hỗ trợ và tư vấn: Nếu bạn gặp vấn đề hoặc cần hỗ trợ trong việc sử dụng Eudsys, bạn có thể tìm kiếm trợ   giúp thông qua tài liệu hướng dẫn hoặc liên hệ với đội ngũ hỗ trợ của Eudsys để được giúp đỡ.\n\nLưu ý rằng các bước này chỉ là hướng dẫn chung và có thể thay đổi tùy theo phiên bản cụ thể của phần     mềm Eudsys mà bạn đang sử dụng.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("HƯỚNG DẪN SỬ DỤNG PHẦN MỀM EDUSYS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 257, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuongDanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuongDanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuongDanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuongDanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HuongDanJDialog dialog = new HuongDanJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
